### ISSUE TITLE
FR:  Clear feature

### ISSUE THREAD

**Issue by DigiAngel** [limbenjamin/TCPHound#1]
I use this great application when running malware to quickly match a pid with traffic.  Would be nice if there could be a clear feature to clear out the closed connections.  Thank you!

**Comment by limbenjamin** [comment]
Hi DigiAngel, that sounds useful to reduce clutter. But it will also clear out closed connection made by running malware. Is it what you intend?

**Comment by DigiAngel** [comment]
Yes indeed...chances are VERY good I'm packet capturing anyway ;)  Additionally, I could always export first, then clear.

**Comment by limbenjamin** [comment]
Feature added in v1.4. Closing issue.

https://github.com/limbenjamin/TCPHound/commit/69180cb3b475f26fc47e1d8bd8525c138e0dd890

**Comment by DigiAngel** [comment]
Thank you! However...how does one clear the display?  I don't see any new right-click or menu options?

**Comment by limbenjamin** [comment]
![Untitled](https://user-images.githubusercontent.com/3461825/67783825-c731fa80-faa5-11e9-8fed-9d2701ffde0b.png)

**Comment by DigiAngel** [comment]
I do not have that option on 1.4....

**Comment by DigiAngel** [comment]
Hrmm...well that's interesting...I do have that on one machine, let me copy that over.

**Comment by DigiAngel** [comment]
Ah...apparently I had an old 1.4 :)  Seeing it now thanks so much..super awesome!
