### ISSUE TITLE
Image name, AS info, full path are empty

### ISSUE THREAD

**Issue by mindracer13** [limbenjamin/TCPHound#2]
This is EXACTLY what I've been looking for!

But unfortunately on windows server 2022 it doesn't show the above info, all these columns are blank.

**Comment by limbenjamin** [comment]
It works on my Windows 10 and Windows 11 PC. Unfortunately, I don't have a Server 2022 image to test this on.

You can try out TCPLogView. https://www.nirsoft.net/utils/tcp_log_view.html
